version: "3"
services:
  db:
    image: "postgres"
    container_name: "blog_pdb"
    environment:
      - POSTGRES_USER="${DB_USER}"
      - POSTGRES_PASSWORD="${DB_PASSWORD}"
      - POSTGRES_DB="${DB_NAME}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ~/docker/images-data/blog-pg-db:/var/lib/postgresql/data
